name: Deploy MyAPP
run-name: ${{ github.actor }} is deploying MyAPP 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-MyAPP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Config BackEnd file
        run: |
          sed -i 's/_USER_/${{ secrets.DB_USERNAME }}/g' backend/myapi.py
          sed -i 's/_PASSWORD_/${{ secrets.DB_PASSWORD }}/g' backend/myapi.py
          sed -i 's/_HOST_/${{ secrets.DB_HOST }}/g' backend/myapi.py
          sed -i 's/_DBNAME_/${{ secrets.DB_NAME }}/g' backend/myapi.py

      - name: Deploy BackEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "backend/myapi.py"
          target: "/home/ubuntu/myapp/"
          strip_components: 1

      - name: Config FrontEnd file
        run: |
          sed -i 's/_API_ADDRESS_/${{ secrets.HOST }}/g' frontend/index.html

      - name: Deploy FrontEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "frontend/index.html"
          target: "/var/www/html/"
          strip_components: 1
